#!/usr/bin/env python3
"""Build immutable DODGE Example Hub artifacts from the Standard 52 resolver."""
from __future__ import annotations
import argparse,hashlib,importlib.util,json
from pathlib import Path
from reportlab.lib.colors import HexColor,black,red,white
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen.canvas import Canvas
ROOT=Path(__file__).resolve().parents[1]
EXAMPLE=ROOT/"draft"/"v0.2.1"/"examples"/"standard-52-card-deck"
PUBLIC=ROOT/"examples"; GAME_ID="standard-52-card-deck"
def load_resolver():
    spec=importlib.util.spec_from_file_location("standard_52_resolver",EXAMPLE/"resolve.py"); module=importlib.util.module_from_spec(spec); assert spec.loader; spec.loader.exec_module(module); return module
def write_json(path,value): path.parent.mkdir(parents=True,exist_ok=True); path.write_text(json.dumps(value,indent=2,ensure_ascii=False)+"\n",encoding="utf-8")
def draw_card(c,card,x,y):
    width,height=2.5*inch,3.5*inch; color=red if card["color"]=="red" else black
    c.setStrokeColor(HexColor("#252936"));c.setLineWidth(.8);c.roundRect(x,y,width,height,8,stroke=1,fill=0);c.setFillColor(color)
    c.setFont("Helvetica-Bold",22);c.drawString(x+12,y+height-28,card["rank_label"]);c.setFont("Helvetica",22);c.drawString(x+13,y+height-52,card["suit_symbol"]);c.setFont("Helvetica-Bold",52);c.drawCentredString(x+width/2,y+height/2-18,card["suit_symbol"])
    c.saveState();c.translate(x+width-12,y+30);c.rotate(180);c.setFont("Helvetica-Bold",22);c.drawString(0,0,card["rank_label"]);c.setFont("Helvetica",22);c.drawString(1,-24,card["suit_symbol"]);c.restoreState()
def draw_back(c,x,y):
    width,height=2.5*inch,3.5*inch;c.setFillColor(HexColor("#171923"));c.setStrokeColor(HexColor("#252936"));c.roundRect(x,y,width,height,8,stroke=1,fill=1);c.setFillColor(white);c.setFont("Helvetica-Bold",18);c.drawCentredString(x+width/2,y+height/2+8,"DODGE");c.setFont("Helvetica",8);c.drawCentredString(x+width/2,y+height/2-10,"STANDARD 52")
def build_pdf(path,resolved,source_sha):
    path.parent.mkdir(parents=True,exist_ok=True);c=Canvas(str(path),pagesize=letter,pageCompression=1,invariant=1);c.setTitle("DODGE Standard 52-card deck PnP");c.setAuthor("DODGE Example Hub")
    positions=((.55*inch,4.15*inch),(3.05*inch,4.15*inch),(5.55*inch,4.15*inch),(.55*inch,.55*inch),(3.05*inch,.55*inch),(5.55*inch,.55*inch))
    cards=resolved["cards"]
    for sheet,start in enumerate(range(0,len(cards),6),1):
        chunk=cards[start:start+6]
        for slot,card in enumerate(chunk):draw_card(c,card,*positions[slot])
        c.setFillColor(HexColor("#596174"));c.setFont("Helvetica",5);c.drawString(.55*inch,.25*inch,f"DODGE source {source_sha} · front sheet {sheet}/9");c.showPage()
        for slot in range(len(chunk)):draw_back(c,*positions[slot])
        c.setFillColor(HexColor("#596174"));c.setFont("Helvetica",5);c.drawString(.55*inch,.25*inch,f"DODGE source {source_sha} · back sheet {sheet}/9");c.showPage()
    c.save()
def app_html(short):
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Standard 52 · DODGE Example</title><link rel="stylesheet" href="../../../../hub.css"></head><body><nav class="top"><a href="../../../">← Example Hub</a><span>Component Example</span></nav><main class="game-shell"><header class="hero compact"><p class="eyebrow">DODGE 0.2.1 · BUILD {short}</p><h1>Standard 52</h1><p>A generic deck runtime driven by one resolved DODGE scene.</p></header><section class="authority"><h2>Authority boundary</h2><div id="identity" class="facts"></div><p><strong>Executable:</strong> shuffle, draw without replacement, discard, reset.</p><p><strong>Not defined:</strong> game setup, turns, scoring, or win conditions.</p></section><section class="table"><div><h2>Deck <span id="deckCount"></span></h2><div id="deck" class="deck-stack"></div></div><div><h2>Drawn card</h2><div id="drawn" class="card-slot"></div></div><div><h2>Discard <span id="discardCount"></span></h2><div id="discard" class="card-slot"></div></div></section><div class="controls"><button id="shuffle">Shuffle</button><button id="draw">Draw</button><button id="discardButton">Discard drawn</button><button id="reset" class="quiet-button">Reset declared order</button></div><section><h2>Resolved inventory</h2><div id="inventory" class="inventory"></div></section></main><script type="module" src="./app.js"></script></body></html>'''
def app_js():
    return '''const model=await fetch("./resolved.json").then(r=>{if(!r.ok)throw new Error(`resolved model: ${r.status}`);return r.json()});const declared=model.cards.map(c=>({...c}));let deck=declared.map(c=>({...c})),drawn=null,discard=[];const $=id=>document.getElementById(id);function cardElement(card,small=false){const el=document.createElement("article");el.className=`playing-card ${card.color} ${small?"small":""}`;el.innerHTML=`<span class="corner">${card.rank_label}<br>${card.suit_symbol}</span><strong>${card.suit_symbol}</strong><span class="corner bottom">${card.rank_label}<br>${card.suit_symbol}</span>`;el.title=card.name;return el}function render(){$("deckCount").textContent=`(${deck.length})`;$("discardCount").textContent=`(${discard.length})`;$('deck').innerHTML=deck.length?'<div class="card-back">DODGE</div>':'<p>Empty</p>';$('drawn').replaceChildren(...(drawn?[cardElement(drawn)]:[]));$('discard').replaceChildren(...(discard.length?[cardElement(discard.at(-1))]:[]));$('draw').disabled=!deck.length||!!drawn;$('discardButton').disabled=!drawn}function shuffle(){for(let i=deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}render()}$('shuffle').onclick=shuffle;$('draw').onclick=()=>{drawn=deck.shift()||null;render()};$('discardButton').onclick=()=>{if(drawn)discard.push(drawn);drawn=null;render()};$('reset').onclick=()=>{deck=declared.map(c=>({...c}));drawn=null;discard=[];render()};$('identity').innerHTML=`<span>DODGE <code>${model.dodge_version}</code></span><span>Document <code>${model.document_id}</code></span><span>Source <code>${model.document_sha256.slice(0,12)}</code></span><span>Catalog <code>${model.catalog.sha256.slice(0,12)}</code></span>`;for(const card of declared)$('inventory').append(cardElement(card,true));render();'''
def build(source_sha):
    if len(source_sha)<12:raise SystemExit("--source-sha must contain at least 12 hexadecimal characters")
    short=source_sha[:12];resolved=load_resolver().resolve();resolved["dodge_source_sha"]=source_sha;build_dir=PUBLIC/GAME_ID/"builds"/short;build_dir.mkdir(parents=True,exist_ok=True)
    write_json(build_dir/"resolved.json",resolved);(build_dir/"index.html").write_text(app_html(short),encoding="utf-8");(build_dir/"app.js").write_text(app_js(),encoding="utf-8")
    pdf_name=f"standard-52-card-deck-pnp-{short}.pdf";pdf_path=PUBLIC/GAME_ID/"downloads"/pdf_name;build_pdf(pdf_path,resolved,source_sha);pdf_sha=hashlib.sha256(pdf_path.read_bytes()).hexdigest()
    tts_name=f"standard-52-card-deck-tts-{short}.json";tts_path=PUBLIC/GAME_ID/"downloads"/tts_name;write_json(tts_path,{"status":"placeholder","message":"The shared TTS adapter is not yet converged. This file reserves the target without claiming a playable package.","source_sha":source_sha,"dodge_document_sha256":resolved["document_sha256"],"catalog_sha256":resolved["catalog"]["sha256"],"ordered_card_ids":[c["id"] for c in resolved["cards"]]});tts_sha=hashlib.sha256(tts_path.read_bytes()).hexdigest()
    build_meta={"format":"dodge-example-build.v1","game_id":GAME_ID,"classification":"component-example","source_sha":source_sha,"short_sha":short,"dodge_version":resolved["dodge_version"],"dodge_source_sha":source_sha,"dodge_document_sha256":resolved["document_sha256"],"catalog_sha256":resolved["catalog"]["sha256"],"resolved_model_sha256":hashlib.sha256((build_dir/"resolved.json").read_bytes()).hexdigest(),"targets":{"web":{"status":"implemented","url":f"./builds/{short}/index.html"},"pnp":{"status":"implemented","url":f"./downloads/{pdf_name}","sha256":pdf_sha},"tts":{"status":"placeholder","url":f"./downloads/{tts_name}","sha256":tts_sha}},"executable_semantics":["shuffle","draw-without-replacement","discard","reset-declared-order"],"unsupported_semantics":["game setup","turn structure","scoring","win conditions"]}
    write_json(build_dir/"build.json",build_meta);versions_path=PUBLIC/GAME_ID/"versions.json"
    try:versions=json.loads(versions_path.read_text()).get("versions",[])
    except FileNotFoundError:versions=[]
    versions=[v for v in versions if v.get("source_sha")!=source_sha];versions.insert(0,{"source_sha":source_sha,"short_sha":short,"label":f"Build {short}","path":f"./builds/{short}/index.html"});write_json(versions_path,{"format":"dodge-example-versions.v1","current":source_sha,"versions":versions});write_json(PUBLIC/GAME_ID/"latest.json",build_meta)
    hub_targets={"web":{"status":"implemented","url":f"./examples/{GAME_ID}/builds/{short}/index.html"},"pnp":{"status":"implemented","url":f"./examples/{GAME_ID}/downloads/{pdf_name}"},"tts":{"status":"placeholder","url":f"./examples/{GAME_ID}/downloads/{tts_name}"}}
    entries=[{"id":GAME_ID,"title":"Standard 52-card deck","classification":"component-example","summary":"Ordered and shuffleable canonical inventory with a shared back.","dodge_version":"0.2.1","dodge_source_sha":source_sha,"status":"available","latest":f"./examples/{GAME_ID}/builds/{short}/index.html","versions":f"./examples/{GAME_ID}/versions.json","targets":hub_targets},{"id":"asymmetric-starter-decks","title":"Asymmetric starter decks","classification":"example-game","summary":"Multiple named decks assembled from one catalog.","status":"planned"},{"id":"equipment-requirements","title":"Equipment & requirements","classification":"example-game","summary":"A tiny playable example for equipment, modifiers, choices, and waivers.","status":"planned"},{"id":"locations-search","title":"Locations & search","classification":"example-game","summary":"A small room graph with entry, search, access, and temporary effects.","status":"planned"},{"id":"digitropolis","title":"Digitropolis","classification":"example-game","summary":"Federated richer card, stat, and icon example.","status":"planned-federated"},{"id":"wretched-demesne","title":"Wretched Demesne","classification":"example-game","summary":"Federated advanced DODGE implementation and convergence reference.","status":"planned-federated"},{"id":"rule-vocabulary","title":"Rule vocabulary fixtures","classification":"specification-lab","summary":"Validated conformance fixtures; not presented as finished games.","status":"available","latest":"./draft/v0.2.1/examples/"}]
    write_json(PUBLIC/"catalog.json",{"format":"dodge-example-hub.v1","current_source_sha":source_sha,"entries":entries});print(f"built {GAME_ID} {short}: 52 cards, Web, PnP, TTS placeholder")
def main():
    p=argparse.ArgumentParser();p.add_argument("--source-sha",required=True);build(p.parse_args().source_sha)
if __name__=="__main__":main()
